/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLettersRouteImport } from './routes/_authenticated/letters'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedCadetsIndexRouteImport } from './routes/_authenticated/cadets.index'
import { Route as AuthenticatedCadetsCadetIdRouteImport } from './routes/_authenticated/cadets.$cadetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLettersRoute = AuthenticatedLettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadetsIndexRoute =
  AuthenticatedCadetsIndexRouteImport.update({
    id: '/cadets/',
    path: '/cadets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadetsCadetIdRoute =
  AuthenticatedCadetsCadetIdRouteImport.update({
    id: '/cadets/$cadetId',
    path: '/cadets/$cadetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/letters': typeof AuthenticatedLettersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/cadets/$cadetId': typeof AuthenticatedCadetsCadetIdRoute
  '/cadets/': typeof AuthenticatedCadetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/letters': typeof AuthenticatedLettersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/cadets/$cadetId': typeof AuthenticatedCadetsCadetIdRoute
  '/cadets': typeof AuthenticatedCadetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/letters': typeof AuthenticatedLettersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/cadets/$cadetId': typeof AuthenticatedCadetsCadetIdRoute
  '/_authenticated/cadets/': typeof AuthenticatedCadetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/letters'
    | '/reports'
    | '/cadets/$cadetId'
    | '/cadets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/letters'
    | '/reports'
    | '/cadets/$cadetId'
    | '/cadets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/attendance'
    | '/_authenticated/dashboard'
    | '/_authenticated/letters'
    | '/_authenticated/reports'
    | '/_authenticated/cadets/$cadetId'
    | '/_authenticated/cadets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/letters': {
      id: '/_authenticated/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof AuthenticatedLettersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadets/': {
      id: '/_authenticated/cadets/'
      path: '/cadets'
      fullPath: '/cadets/'
      preLoaderRoute: typeof AuthenticatedCadetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadets/$cadetId': {
      id: '/_authenticated/cadets/$cadetId'
      path: '/cadets/$cadetId'
      fullPath: '/cadets/$cadetId'
      preLoaderRoute: typeof AuthenticatedCadetsCadetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLettersRoute: typeof AuthenticatedLettersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedCadetsCadetIdRoute: typeof AuthenticatedCadetsCadetIdRoute
  AuthenticatedCadetsIndexRoute: typeof AuthenticatedCadetsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLettersRoute: AuthenticatedLettersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedCadetsCadetIdRoute: AuthenticatedCadetsCadetIdRoute,
  AuthenticatedCadetsIndexRoute: AuthenticatedCadetsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
